version: '3.2'
services:
  wordpress:
    container_name: 'local-wordpress'
    image: wordpress
    restart: always
    links:
      - db:mysql
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_USER: root
      WORDPRESS_DB_name: wordpress
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
      - ../.:/var/www/html/wp-content/plugins/wp-plugin-creativecommons
      # Ignore these directories when mounting the root into /var/www/html/wp-content/plugins/wp-plugin-creativecommons so they are not included
      - /var/www/html/wp-content/plugins/wp-plugin-creativecommons/dev/wordpress
      - /var/www/html/wp-content/plugins/wp-plugin-creativecommons/dev/db
  db:
    container_name: 'local-wordpress-db'
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
